// import Details from '@/components/Details/Details'
// import Main from '@/components/Main/Main'
// import Sidebar from '@/components/Sidebar/Sidebar'
import Head from 'next/head'
import Details from './Details/Details'
import Main from './Main/Main'
import Sidebar from './Sidebar/Sidebar'

const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex min-h-screen">
                <Sidebar />
                <Main>{children}</Main>
                <Details />
            </div>
        </div>
    )
}

export default Layout
